
# only check for the targets we currently publish
targets = [
  { triple = "x86_64-apple-darwin" },
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
  { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
# FIXME: remove this if/when clap changes to is-terminal, atty is
# patched, or we migrated to an MSRV of 1.66.0.
ignore = [
    "RUSTSEC-2021-0145",
]

[bans]
multiple-versions = "deny"
deny = []
skip-tree = [
    { name = "tempfile", version = "=3.4.0", depth = 2 },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[licenses]
# need this since to suppress errors in case we add crates with these allowed licenses
unused-allowed-license = "allow"
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "MIT",
  "CC0-1.0",
  "ISC",
  "0BSD",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Unlicense",
  "Unicode-DFS-2016",
]

[licenses.private]
ignore = true
